### ISSUE TITLE
Το κείμενο δεν είναι γραμμένο στα ελληνικά

### ISSUE THREAD

**Issue by sebdesign** [greecejs/docs#1]
Μιας και οι συναντήσεις γίνονται στην Ελλάδα, οι πλειοψηφία των ανθρώπων που δουλεύουν σε ελληνικές start-up είναι Έλληνες, οι υπεύθυνοι του GreeceJS είναι Έλληνες, σε τι εξυπηρετεί που το κείμενο είναι γραμμένο στα αγγλικά;

**Comment by jmike** [comment]
@sebdesign έχεις δίκιο - είμαστε Έλληνες. Όμως η κοινότητα των startups στην Ελλάδα, έτσι όπως την έχω γνωρίσει εγώ, είναι ιδιαιτέρως φιλική στην αγγλική. Είναι σύνηθες φαινόμενο να ανταλλάσονται e-mail στα αγγλικά ακόμα και μεταξύ Ελλήνων. Υπάρχουν διάφοροι λόγοι που συμβαίνει αυτό, π.χ. η εταιρεία έχει προσανατολισμό προς τα έξω, για να βρει συνεργάτες, πελάτες και επενδυτές.

Επειδή λοιπόν το συγκεκριμένο 1 document απευθύνεται στις αγγλομαθείς startups (Open letter to startups) θεώρησα πως είναι καλύτερο να το γράψω στα αγγλικά. Τα επόμενα που θα έρθουν και θα απευθύνονται σε developers και social media, θα δοκιμάσω να τα γράψω στα ελληνικά :-)

**Comment by sebdesign** [comment]
@jmike σ'ευχαριστώ για την απάντησή σου. Σου απαντώ πολύ καθυστερημένα.

Κι εγώ έχω υπάρξει "θύμα" αυτού του φαινομένου, π.χ. έχω λάβει emails στα αγγλικά από έλληνες και ελληνικές εταιρείες. Ακόμα κι εγώ που παρουσιάζω την δουλειά μου στα αγγλικά στην ιστοσελίδα μου, για τους ίδιους λόγους που αναφέρεις κι εσύ, νιώθω άβολα όταν κάποιος (έλληνας) με προσεγγίζει άμεσα ή έμμεσα στα αγγλικά.

Εάν κάποιος άνθρωπος ή κοινότητα επικοινωνεί μαζί μου για κάτι που πιθανόν με ενδιαφέρει, από ευγένεια/σεβασμό και μόνο θα μπορούσε να το κάνει στη γλώσσα που είναι πιο άμεση και εύκολη για όλους μας. 

Προφανώς δε θίχτηκα προσωπικά από αυτή την ανοιχτή επιστολή, ούτε θεωρώ τον εαυτό μου ελληνάρα, είμαι δίγλωσσος και έχω διπλή ιθαγένεια. Αλλά ως άνθρωποι της τεχνολογίας και της καινοτομίας, είναι κρίμα να συμβιβάζουμε την επικοινωνία μεταξύ μας επειδή κάποιοι φορείς "είναι ιδιαίτερα φιλικοί στην αγγλική". Όπως αναπτύσσουμε λύσεις και προϊόντα με γνώμονα το usability για τον τελικό χρήστη, έτσι οφείλουμε στην κοινότητά (μας) να επικοινωνούμε πιο άμεσα, πιο ανοιχτά, πιο ~~relevant~~ σχετικά.

Εύχομαι να υπάρξει ανοιχτή επιστολή που να απευθύνεται και στις ελληνομαθείς startups, και σε έλληνες developers και όχι μόνο στη wannabe silicon valley. :)

`</rant>`
